name:                georgevirtualmachine
version:             0.1.0.0
github:              "githubuser/georgemachine"
license:             MIT 
author:              "Georg Ziegler"
maintainer:          "georgjziegler@gmail.com"
copyright:           "2019 Georg Ziegler"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/georgemachine#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  georgevm:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - georgevirtualmachine

tests:
  georgemachine-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - georgemachine
